#define ENCODER_A_PINS { GP4 }
#define ENCODER_B_PINS { GP2 }

#define WS2812_DI_PIN GP0
#define RGBLIGHT_LED_COUNT 9
#define RGBLIGHT_LIMIT_VAL 120

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7

#define OLED_TIMEOUT 0
